#ifndef GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H
#define GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H

enum Cutscenes
{
    PETALBURG_TEST_ONE,
    PETALBURG_TEST_TWO,
    CUTSCENE_COUNT,
};

#endif // GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H