#ifndef GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H
#define GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H

enum Cutscenes
{
    PLAYER_HOUSE_WAKE_UP,
    CUTSCENE_COUNT,
};

#endif // GUARD_IKIGAI_CONSTANTS_GUARD_CUTSCENE_H