#ifndef GUARD_CONSTANTS_DYNAMIC_MUSIC_H
#define GUARD_CONSTANTS_DYNAMIC_MUSIC_H

enum DynamicMusicInstruments
{
    INSTRUMENT_ACCORDIAN,
    INSTRUMENT_KEYTAR,
    INSTRUMENT_ERHU,
    // INSTRUMENT_GUITAR,
    INSTRUMENT_WHISTLE,
    INSTRUMENT_FLUTE,
    INSTRUMENT_ALL,
    INSTRUMENT_COUNT,
};

#endif // GUARD_CONSTANTS_DYNAMIC_MUSIC_H