#ifndef GUARD_CONSTANTS_DYNAMIC_MUSIC_H
#define GUARD_CONSTANTS_DYNAMIC_MUSIC_H

enum DynamicMusicInstruments
{
    INSTRUMENT_ACCORDIAN,
    INSTRUMENT_COUNT,
};

#endif // GUARD_CONSTANTS_DYNAMIC_MUSIC_H