#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

#include "constants/event_objects.h"
#include "constants/species.h"

#define TAG_MUGSHOT 0x9000

// Mugshot Types
#define MUGSHOT_DEFINED     0
#define MUGSHOT_NPC         1
#define MUGSHOT_PLAYER      2
#define MUGSHOT_PMD         3
#define MUGSHOT_FOLLOWER    4
#define MUGSHOT_TYPES       5

// Follower Mugshot Settings
#define MUGSHOT_FOLLOWER_PLACEHOLDER    0
#define MUGSHOT_FOLLOWER_ON             1
#define MUGSHOT_FOLLOWER_OFF            2

// Mugshot IDs
#define MUGSHOT_AUTO_GRAPHICS_ID            NUM_OBJ_EVENT_GFX
#define MUGSHOT_KOLE                        OBJ_EVENT_GFX_KOLE_NORMAL
#define MUGSHOT_ANKA                        OBJ_EVENT_GFX_ANKA_NORMAL
#define MUGSHOT_SAMUEL                      OBJ_EVENT_GFX_SAMUEL
#define MUGSHOT_LAUREN                      OBJ_EVENT_GFX_LAUREN
#define MUGSHOT_THOMAS                      OBJ_EVENT_GFX_THOMAS
#define MUGSHOT_HANNAH                      OBJ_EVENT_GFX_HANNAH
#define MUGSHOT_KATIE                       OBJ_EVENT_GFX_KATIE
#define MUGSHOT_LOUIS                       OBJ_EVENT_GFX_LOUIS
#define MUGSHOT_GEORGIA                     OBJ_EVENT_GFX_GEORGIA
#define MUGSHOT_CAPTAIN                     OBJ_EVENT_GFX_CAPTAIN
#define MUGSHOT_STEVEN                      OBJ_EVENT_GFX_STEVEN_NEW
#define MUGSHOT_CYNTHIA                     OBJ_EVENT_GFX_CYNTHIA
#define MUGSHOT_N                           OBJ_EVENT_GFX_N
#define MUGSHOT_SUBSTITUTE_DOLL             OBJ_EVENT_GFX_SPECIES(NONE)
#define MUGSHOT_BULBASAUR                   OBJ_EVENT_GFX_SPECIES(BULBASAUR)
#define MUGSHOT_BULBASAUR_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(BULBASAUR)
#define MUGSHOT_IVYSAUR                     OBJ_EVENT_GFX_SPECIES(IVYSAUR)
#define MUGSHOT_IVYSAUR_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(IVYSAUR)
#define MUGSHOT_VENUSAUR                    OBJ_EVENT_GFX_SPECIES(VENUSAUR)
#define MUGSHOT_VENUSAUR_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(VENUSAUR)
#define MUGSHOT_CHARMANDER                  OBJ_EVENT_GFX_SPECIES(CHARMANDER)
#define MUGSHOT_CHARMANDER_SHINY            OBJ_EVENT_GFX_SPECIES_SHINY(CHARMANDER)
#define MUGSHOT_CHARMELEON                  OBJ_EVENT_GFX_SPECIES(CHARMELEON)
#define MUGSHOT_CHARMELEON_SHINY            OBJ_EVENT_GFX_SPECIES_SHINY(CHARMELEON)
#define MUGSHOT_CHARIZARD                   OBJ_EVENT_GFX_SPECIES(CHARIZARD)
#define MUGSHOT_CHARIZARD_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(CHARIZARD)
#define MUGSHOT_SQUIRTLE                    OBJ_EVENT_GFX_SPECIES(SQUIRTLE)
#define MUGSHOT_SQUIRTLE_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(SQUIRTLE)
#define MUGSHOT_WARTORTLE                   OBJ_EVENT_GFX_SPECIES(WARTORTLE)
#define MUGSHOT_WARTORTLE_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(WARTORTLE)
#define MUGSHOT_BLASTOISE                   OBJ_EVENT_GFX_SPECIES(BLASTOISE)
#define MUGSHOT_BLASTOISE_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(BLASTOISE)
#define MUGSHOT_PICHU                       OBJ_EVENT_GFX_SPECIES(PICHU)
#define MUGSHOT_PICHU_SHINY                 OBJ_EVENT_GFX_SPECIES_SHINY(PICHU)
#define MUGSHOT_PIKACHU                     OBJ_EVENT_GFX_SPECIES(PIKACHU)
#define MUGSHOT_PIKACHU_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(PIKACHU)
#define MUGSHOT_RAICHU                      OBJ_EVENT_GFX_SPECIES(RAICHU)
#define MUGSHOT_RAICHU_SHINY                OBJ_EVENT_GFX_SPECIES_SHINY(RAICHU)
#define MUGSHOT_EEVEE                       OBJ_EVENT_GFX_SPECIES(EEVEE)
#define MUGSHOT_EEVEE_SHINY                 OBJ_EVENT_GFX_SPECIES_SHINY(EEVEE)
#define MUGSHOT_RELICANTH                   OBJ_EVENT_GFX_SPECIES(RELICANTH)
#define MUGSHOT_RELICANTH_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(RELICANTH)
#define MUGSHOT_INFERNAPE                   OBJ_EVENT_GFX_SPECIES(INFERNAPE)
#define MUGSHOT_INFERNAPE_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(INFERNAPE)
#define MUGSHOT_ZOROARK                     OBJ_EVENT_GFX_SPECIES(ZOROARK)
#define MUGSHOT_ZOROARK_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(ZOROARK)
#define MUGSHOT_ESPURR                      OBJ_EVENT_GFX_SPECIES(ESPURR)
#define MUGSHOT_ESPURR_SHINY                OBJ_EVENT_GFX_SPECIES_SHINY(ESPURR)
#define MUGSHOT_ROCKRUFF                    OBJ_EVENT_GFX_SPECIES(ROCKRUFF)
#define MUGSHOT_ROCKRUFF_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(ROCKRUFF)
#define MUGSHOT_METAGROSS                   OBJ_EVENT_GFX_SPECIES(METAGROSS)
#define MUGSHOT_METAGROSS_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(METAGROSS)
#define MUGSHOT_GARCHOMP                    OBJ_EVENT_GFX_SPECIES(GARCHOMP)
#define MUGSHOT_GARCHOMP_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(GARCHOMP)
#define MUGSHOT_AMOONGUSS                   OBJ_EVENT_GFX_SPECIES(AMOONGUSS)
#define MUGSHOT_AMOONGUSS_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(AMOONGUSS)
#define MUGSHOT_WHIMSICOTT                  OBJ_EVENT_GFX_SPECIES(WHIMSICOTT)
#define MUGSHOT_WHIMSICOTT_SHINY            OBJ_EVENT_GFX_SPECIES_SHINY(WHIMSICOTT)
#define MUGSHOT_GURDURR                     OBJ_EVENT_GFX_SPECIES(GURDURR)
#define MUGSHOT_GURDURR_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(GURDURR)
#define MUGSHOT_RIBOMBEE                    OBJ_EVENT_GFX_SPECIES(RIBOMBEE)
#define MUGSHOT_RIBOMBEE_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(RIBOMBEE)

// Emotes
// Also set in charmap.txt
#define EMOTE_NORMAL        0
#define EMOTE_ANGRY         1
#define EMOTE_CRYING        2
#define EMOTE_DETERMINED    3
#define EMOTE_DIZZY         4
#define EMOTE_HAPPY         5
#define EMOTE_INSPIRED      6
#define EMOTE_JOYOUS        7
#define EMOTE_PAIN          8
#define EMOTE_SAD           9
#define EMOTE_SHOUTING      10
#define EMOTE_SIGH          11
#define EMOTE_STUNNED       12
#define EMOTE_SURPRISED     13
#define EMOTE_TEARY         14
#define EMOTE_WORRIED       15
#define EMOTE_SPECIAL       16
#define EMOTE_COUNT         17

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
