#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

#include "constants/event_objects.h"
#include "constants/species.h"

#define TAG_MUGSHOT 0x9000

// Mugshot Types
#define MUGSHOT_DEFINED     0
#define MUGSHOT_NPC         1
#define MUGSHOT_PLAYER      2
#define MUGSHOT_PMD         3
#define MUGSHOT_FOLLOWER    4
#define MUGSHOT_TYPES       5

// Follower Mugshot Settings
#define MUGSHOT_FOLLOWER_PLACEHOLDER    0
#define MUGSHOT_FOLLOWER_ON             1
#define MUGSHOT_FOLLOWER_OFF            2

// Mugshot IDs
#define MUGSHOT_AUTO_GRAPHICS_ID            NUM_OBJ_EVENT_GFX
#define MUGSHOT_KOLE                        OBJ_EVENT_GFX_KOLE_NORMAL
#define MUGSHOT_ANKA                        OBJ_EVENT_GFX_ANKA_NORMAL
#define MUGSHOT_SAMUEL                      OBJ_EVENT_GFX_SAMUEL
#define MUGSHOT_LAUREN                      OBJ_EVENT_GFX_LAUREN
#define MUGSHOT_THOMAS                      OBJ_EVENT_GFX_THOMAS
#define MUGSHOT_HANNAH                      OBJ_EVENT_GFX_HANNAH
#define MUGSHOT_KATIE                       OBJ_EVENT_GFX_KATIE
#define MUGSHOT_LOUIS                       OBJ_EVENT_GFX_LOUIS
#define MUGSHOT_GEORGIA                     OBJ_EVENT_GFX_GEORGIA
#define MUGSHOT_CAPTAIN                     OBJ_EVENT_GFX_CAPTAIN
#define MUGSHOT_DIEGO                       OBJ_EVENT_GFX_DIEGO
#define MUGSHOT_STEVEN                      OBJ_EVENT_GFX_STEVEN_GEN4
#define MUGSHOT_CYNTHIA                     OBJ_EVENT_GFX_CYNTHIA
#define MUGSHOT_N                           OBJ_EVENT_GFX_N
#define MUGSHOT_ASH                         OBJ_EVENT_GFX_ASH_KETCHUM
#define MUGSHOT_SUBSTITUTE_DOLL             OBJ_EVENT_GFX_SPECIES(NONE)
#define MUGSHOT_BULBASAUR                   OBJ_EVENT_GFX_SPECIES(BULBASAUR)
#define MUGSHOT_BULBASAUR_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(BULBASAUR)
#define MUGSHOT_IVYSAUR                     OBJ_EVENT_GFX_SPECIES(IVYSAUR)
#define MUGSHOT_IVYSAUR_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(IVYSAUR)
#define MUGSHOT_VENUSAUR                    OBJ_EVENT_GFX_SPECIES(VENUSAUR)
#define MUGSHOT_VENUSAUR_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(VENUSAUR)
#define MUGSHOT_CHARMANDER                  OBJ_EVENT_GFX_SPECIES(CHARMANDER)
#define MUGSHOT_CHARMANDER_SHINY            OBJ_EVENT_GFX_SPECIES_SHINY(CHARMANDER)
#define MUGSHOT_CHARMELEON                  OBJ_EVENT_GFX_SPECIES(CHARMELEON)
#define MUGSHOT_CHARMELEON_SHINY            OBJ_EVENT_GFX_SPECIES_SHINY(CHARMELEON)
#define MUGSHOT_CHARIZARD                   OBJ_EVENT_GFX_SPECIES(CHARIZARD)
#define MUGSHOT_CHARIZARD_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(CHARIZARD)
#define MUGSHOT_SQUIRTLE                    OBJ_EVENT_GFX_SPECIES(SQUIRTLE)
#define MUGSHOT_SQUIRTLE_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(SQUIRTLE)
#define MUGSHOT_WARTORTLE                   OBJ_EVENT_GFX_SPECIES(WARTORTLE)
#define MUGSHOT_WARTORTLE_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(WARTORTLE)
#define MUGSHOT_BLASTOISE                   OBJ_EVENT_GFX_SPECIES(BLASTOISE)
#define MUGSHOT_BLASTOISE_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(BLASTOISE)
#define MUGSHOT_PICHU                       OBJ_EVENT_GFX_SPECIES(PICHU)
#define MUGSHOT_PICHU_SHINY                 OBJ_EVENT_GFX_SPECIES_SHINY(PICHU)
#define MUGSHOT_PIKACHU                     OBJ_EVENT_GFX_SPECIES(PIKACHU)
#define MUGSHOT_PIKACHU_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(PIKACHU)
#define MUGSHOT_RAICHU                      OBJ_EVENT_GFX_SPECIES(RAICHU)
#define MUGSHOT_RAICHU_SHINY                OBJ_EVENT_GFX_SPECIES_SHINY(RAICHU)
#define MUGSHOT_EEVEE                       OBJ_EVENT_GFX_SPECIES(EEVEE)
#define MUGSHOT_EEVEE_SHINY                 OBJ_EVENT_GFX_SPECIES_SHINY(EEVEE)
#define MUGSHOT_LAPRAS                      OBJ_EVENT_GFX_SPECIES(LAPRAS)
#define MUGSHOT_LAPRAS_SHINY                OBJ_EVENT_GFX_SPECIES_SHINY(LAPRAS)
#define MUGSHOT_RELICANTH                   OBJ_EVENT_GFX_SPECIES(RELICANTH)
#define MUGSHOT_RELICANTH_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(RELICANTH)
#define MUGSHOT_INFERNAPE                   OBJ_EVENT_GFX_SPECIES(INFERNAPE)
#define MUGSHOT_INFERNAPE_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(INFERNAPE)
#define MUGSHOT_ZOROARK                     OBJ_EVENT_GFX_SPECIES(ZOROARK)
#define MUGSHOT_ZOROARK_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(ZOROARK)
#define MUGSHOT_ESPURR                      OBJ_EVENT_GFX_SPECIES(ESPURR)
#define MUGSHOT_ESPURR_SHINY                OBJ_EVENT_GFX_SPECIES_SHINY(ESPURR)
#define MUGSHOT_ROCKRUFF                    OBJ_EVENT_GFX_SPECIES(ROCKRUFF)
#define MUGSHOT_ROCKRUFF_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(ROCKRUFF)
#define MUGSHOT_METAGROSS                   OBJ_EVENT_GFX_SPECIES(METAGROSS)
#define MUGSHOT_METAGROSS_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(METAGROSS)
#define MUGSHOT_GARCHOMP                    OBJ_EVENT_GFX_SPECIES(GARCHOMP)
#define MUGSHOT_GARCHOMP_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(GARCHOMP)
#define MUGSHOT_AMOONGUSS                   OBJ_EVENT_GFX_SPECIES(AMOONGUSS)
#define MUGSHOT_AMOONGUSS_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(AMOONGUSS)
#define MUGSHOT_WHIMSICOTT                  OBJ_EVENT_GFX_SPECIES(WHIMSICOTT)
#define MUGSHOT_WHIMSICOTT_SHINY            OBJ_EVENT_GFX_SPECIES_SHINY(WHIMSICOTT)
#define MUGSHOT_GURDURR                     OBJ_EVENT_GFX_SPECIES(GURDURR)
#define MUGSHOT_GURDURR_SHINY               OBJ_EVENT_GFX_SPECIES_SHINY(GURDURR)
#define MUGSHOT_RIBOMBEE                    OBJ_EVENT_GFX_SPECIES(RIBOMBEE)
#define MUGSHOT_RIBOMBEE_SHINY              OBJ_EVENT_GFX_SPECIES_SHINY(RIBOMBEE)
#define MUGSHOT_BAGON                       OBJ_EVENT_GFX_SPECIES(BAGON)
#define MUGSHOT_BAGON_SHINY                 OBJ_EVENT_GFX_SPECIES_SHINY(BAGON)
#define MUGSHOT_CARKOL                      OBJ_EVENT_GFX_SPECIES(CARKOL)
#define MUGSHOT_CARKOL_SHINY                OBJ_EVENT_GFX_SPECIES_SHINY(CARKOL)
#define MUGSHOT_CHARJABUG                   OBJ_EVENT_GFX_SPECIES(CHARJABUG)
#define MUGSHOT_CHARJABUG_SHINY             OBJ_EVENT_GFX_SPECIES_SHINY(CHARJABUG)
#define MUGSHOT_COALOSSAL          OBJ_EVENT_GFX_SPECIES(COALOSSAL)
#define MUGSHOT_COALOSSAL_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(COALOSSAL)


#define MUGSHOT_CORVIKNIGHT          OBJ_EVENT_GFX_SPECIES(CORVIKNIGHT)
#define MUGSHOT_CORVIKNIGHT_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(CORVIKNIGHT)


#define MUGSHOT_CORVISQUIRE          OBJ_EVENT_GFX_SPECIES(CORVISQUIRE)
#define MUGSHOT_CORVISQUIRE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(CORVISQUIRE)


#define MUGSHOT_DUSCLOPS          OBJ_EVENT_GFX_SPECIES(DUSCLOPS)
#define MUGSHOT_DUSCLOPS_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(DUSCLOPS)


#define MUGSHOT_DUSKNOIR          OBJ_EVENT_GFX_SPECIES(DUSKNOIR)
#define MUGSHOT_DUSKNOIR_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(DUSKNOIR)


#define MUGSHOT_DUSKULL          OBJ_EVENT_GFX_SPECIES(DUSKULL)
#define MUGSHOT_DUSKULL_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(DUSKULL)


#define MUGSHOT_FLABEBE          OBJ_EVENT_GFX_SPECIES(FLABEBE)
#define MUGSHOT_FLABEBE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(FLABEBE)


#define MUGSHOT_FLOETTE          OBJ_EVENT_GFX_SPECIES(FLOETTE)
#define MUGSHOT_FLOETTE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(FLOETTE)


#define MUGSHOT_FLORGES          OBJ_EVENT_GFX_SPECIES(FLORGES)
#define MUGSHOT_FLORGES_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(FLORGES)


#define MUGSHOT_GRIMMSNARL          OBJ_EVENT_GFX_SPECIES(GRIMMSNARL)
#define MUGSHOT_GRIMMSNARL_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(GRIMMSNARL)


#define MUGSHOT_GRUBBIN          OBJ_EVENT_GFX_SPECIES(GRUBBIN)
#define MUGSHOT_GRUBBIN_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(GRUBBIN)


#define MUGSHOT_HATENNA          OBJ_EVENT_GFX_SPECIES(HATENNA)
#define MUGSHOT_HATENNA_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(HATENNA)


#define MUGSHOT_HATTERENE          OBJ_EVENT_GFX_SPECIES(HATTERENE)
#define MUGSHOT_HATTERENE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(HATTERENE)


#define MUGSHOT_HATTREM          OBJ_EVENT_GFX_SPECIES(HATTREM)
#define MUGSHOT_HATTREM_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(HATTREM)


#define MUGSHOT_HERDIER          OBJ_EVENT_GFX_SPECIES(HERDIER)
#define MUGSHOT_HERDIER_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(HERDIER)


#define MUGSHOT_IMPIDIMP          OBJ_EVENT_GFX_SPECIES(IMPIDIMP)
#define MUGSHOT_IMPIDIMP_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(IMPIDIMP)


#define MUGSHOT_KLANG          OBJ_EVENT_GFX_SPECIES(KLANG)
#define MUGSHOT_KLANG_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(KLANG)


#define MUGSHOT_KLINK          OBJ_EVENT_GFX_SPECIES(KLINK)
#define MUGSHOT_KLINK_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(KLINK)


#define MUGSHOT_KLINKLANG          OBJ_EVENT_GFX_SPECIES(KLINKLANG)
#define MUGSHOT_KLINKLANG_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(KLINKLANG)


#define MUGSHOT_KROKOROK          OBJ_EVENT_GFX_SPECIES(KROKOROK)
#define MUGSHOT_KROKOROK_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(KROKOROK)


#define MUGSHOT_KROOKODILE          OBJ_EVENT_GFX_SPECIES(KROOKODILE)
#define MUGSHOT_KROOKODILE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(KROOKODILE)


#define MUGSHOT_LILLIPUP          OBJ_EVENT_GFX_SPECIES(LILLIPUP)
#define MUGSHOT_LILLIPUP_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(LILLIPUP)


#define MUGSHOT_LUXIO          OBJ_EVENT_GFX_SPECIES(LUXIO)
#define MUGSHOT_LUXIO_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(LUXIO)


#define MUGSHOT_LUXRAY          OBJ_EVENT_GFX_SPECIES(LUXRAY)
#define MUGSHOT_LUXRAY_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(LUXRAY)


#define MUGSHOT_MACHAMP          OBJ_EVENT_GFX_SPECIES(MACHAMP)
#define MUGSHOT_MACHAMP_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MACHAMP)


#define MUGSHOT_MACHOKE          OBJ_EVENT_GFX_SPECIES(MACHOKE)
#define MUGSHOT_MACHOKE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MACHOKE)


#define MUGSHOT_MACHOP          OBJ_EVENT_GFX_SPECIES(MACHOP)
#define MUGSHOT_MACHOP_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MACHOP)


#define MUGSHOT_MAGBY          OBJ_EVENT_GFX_SPECIES(MAGBY)
#define MUGSHOT_MAGBY_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MAGBY)


#define MUGSHOT_MAGMAR          OBJ_EVENT_GFX_SPECIES(MAGMAR)
#define MUGSHOT_MAGMAR_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MAGMAR)


#define MUGSHOT_MAGMORTAR          OBJ_EVENT_GFX_SPECIES(MAGMORTAR)
#define MUGSHOT_MAGMORTAR_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MAGMORTAR)


#define MUGSHOT_MAMOSWINE          OBJ_EVENT_GFX_SPECIES(MAMOSWINE)
#define MUGSHOT_MAMOSWINE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MAMOSWINE)


#define MUGSHOT_MORGREM          OBJ_EVENT_GFX_SPECIES(MORGREM)
#define MUGSHOT_MORGREM_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(MORGREM)


#define MUGSHOT_NIDOKING          OBJ_EVENT_GFX_SPECIES(NIDOKING)
#define MUGSHOT_NIDOKING_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(NIDOKING)


#define MUGSHOT_NIDOQUEEN          OBJ_EVENT_GFX_SPECIES(NIDOQUEEN)
#define MUGSHOT_NIDOQUEEN_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(NIDOQUEEN)


#define MUGSHOT_NIDORAN_F          OBJ_EVENT_GFX_SPECIES(NIDORAN_F)
#define MUGSHOT_NIDORAN_F_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(NIDORAN_F)


#define MUGSHOT_NIDORAN_M          OBJ_EVENT_GFX_SPECIES(NIDORAN_M)
#define MUGSHOT_NIDORAN_M_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(NIDORAN_M)


#define MUGSHOT_NIDORINA          OBJ_EVENT_GFX_SPECIES(NIDORINA)
#define MUGSHOT_NIDORINA_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(NIDORINA)


#define MUGSHOT_NIDORINO          OBJ_EVENT_GFX_SPECIES(NIDORINO)
#define MUGSHOT_NIDORINO_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(NIDORINO)


#define MUGSHOT_NUZLEAF          OBJ_EVENT_GFX_SPECIES(NUZLEAF)
#define MUGSHOT_NUZLEAF_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(NUZLEAF)


#define MUGSHOT_PALPITOAD          OBJ_EVENT_GFX_SPECIES(PALPITOAD)
#define MUGSHOT_PALPITOAD_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(PALPITOAD)


#define MUGSHOT_PILOSWINE          OBJ_EVENT_GFX_SPECIES(PILOSWINE)
#define MUGSHOT_PILOSWINE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(PILOSWINE)


#define MUGSHOT_ROLYCOLY          OBJ_EVENT_GFX_SPECIES(ROLYCOLY)
#define MUGSHOT_ROLYCOLY_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(ROLYCOLY)


#define MUGSHOT_ROOKIDEE          OBJ_EVENT_GFX_SPECIES(ROOKIDEE)
#define MUGSHOT_ROOKIDEE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(ROOKIDEE)


#define MUGSHOT_SALAMENCE          OBJ_EVENT_GFX_SPECIES(SALAMENCE)
#define MUGSHOT_SALAMENCE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SALAMENCE)


#define MUGSHOT_SANDILE          OBJ_EVENT_GFX_SPECIES(SANDILE)
#define MUGSHOT_SANDILE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SANDILE)


#define MUGSHOT_SEEDOT          OBJ_EVENT_GFX_SPECIES(SEEDOT)
#define MUGSHOT_SEEDOT_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SEEDOT)


#define MUGSHOT_SEISMITOAD          OBJ_EVENT_GFX_SPECIES(SEISMITOAD)
#define MUGSHOT_SEISMITOAD_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SEISMITOAD)


#define MUGSHOT_SHELGON          OBJ_EVENT_GFX_SPECIES(SHELGON)
#define MUGSHOT_SHELGON_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SHELGON)


#define MUGSHOT_SHIFTRY          OBJ_EVENT_GFX_SPECIES(SHIFTRY)
#define MUGSHOT_SHIFTRY_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SHIFTRY)


#define MUGSHOT_SHINX          OBJ_EVENT_GFX_SPECIES(SHINX)
#define MUGSHOT_SHINX_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SHINX)


#define MUGSHOT_STOUTLAND          OBJ_EVENT_GFX_SPECIES(STOUTLAND)
#define MUGSHOT_STOUTLAND_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(STOUTLAND)


#define MUGSHOT_SWINUB          OBJ_EVENT_GFX_SPECIES(SWINUB)
#define MUGSHOT_SWINUB_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(SWINUB)


#define MUGSHOT_TYMPOLE          OBJ_EVENT_GFX_SPECIES(TYMPOLE)
#define MUGSHOT_TYMPOLE_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(TYMPOLE)


#define MUGSHOT_VIKAVOLT          OBJ_EVENT_GFX_SPECIES(VIKAVOLT)
#define MUGSHOT_VIKAVOLT_SHINY    OBJ_EVENT_GFX_SPECIES_SHINY(VIKAVOLT)

// Emotes
// Also set in charmap.txt
#define EMOTE_NORMAL        0
#define EMOTE_ANGRY         1
#define EMOTE_CRYING        2
#define EMOTE_DETERMINED    3
#define EMOTE_DIZZY         4
#define EMOTE_HAPPY         5
#define EMOTE_INSPIRED      6
#define EMOTE_JOYOUS        7
#define EMOTE_PAIN          8
#define EMOTE_SAD           9
#define EMOTE_SHOUTING      10
#define EMOTE_SIGH          11
#define EMOTE_STUNNED       12
#define EMOTE_SURPRISED     13
#define EMOTE_TEARY         14
#define EMOTE_WORRIED       15
#define EMOTE_SPECIAL       16
#define EMOTE_COUNT         17

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
