#define OPINION_NEUTRAL_BUFFER 20

enum DialogueOption
{
    DIALOGUE_OPTION_TALK,
    DIALOGUE_OPTION_OPINION,
    DIALOGUE_OPTION_ROMANCE,
    DIALOGUE_OPTION_QUESTS,
    DIALOGUE_OPTION_BATTLE,
    DIALOGUE_OPTION_GIFT,
    DIALOGUE_OPTION_GOODBYE,
    DIALOGUE_OPTION_COUNT,
};

enum AttitudeId
{
    ATTITUDE_NEUTRAL,
    ATTITUDE_INSPIRED,
    ATTITUDE_HUMBLE,
    ATTITUDE_DOMINANT,
    ATTITUDE_CYNICAL,
    ATTITUDE_COUNT,
};

enum RelationshipType
{
    RELATIONSHIP_SINGLE,
    RELATIONSHIP_MONOGOMOUS,
    RELATIONSHIP_POLYAMOROUS,
    RELATIONSHIP_POSITIVE = 5,
    RELATIONSHIP_VERY_POSITIVE = 10,
    RELATIONSHIP_EXTREMELY_POSITIVE = 20,
};

enum CharacterId
{
    CHARACTER_DEFAULT,
    MAIN_CHARACTER_SAMUEL,
    MAIN_CHARACTER_LAUREN,
    MAIN_CHARACTER_THOMAS,
    MAIN_CHARACTER_CAPTAIN,
    MAIN_CHARACTER_COUNT,
    SPECIAL_CHARACTER_N,
    CHARACTER_COUNT_TOTAL,
};