enum
{
    DIALOGUE_OPTION_TALK,
    DIALOGUE_OPTION_QUESTS,
    DIALOGUE_OPTION_BATTLE,
    DIALOGUE_OPTION_GOODBYE,
    DIALOGUE_OPTION_COUNT,
};

enum
{
    CHARACTERISTIC_NEUTRAL,
    CHARACTERISTIC_INSPIRED,
    CHARACTERISTIC_HUMBLE,
    CHARACTERISTIC_DOMINAT,
    CHARACTERISTIC_CYNICAL,
    CHARACTERISTIC_COUNT,
};

enum // Up to 256 Character IDs
{
    CHARACTER_DEFAULT,
    CHARACTER_SAMUEL,
    CHARACTER_LAUREN,
    CHARACTER_THOMAS,
    CHARACTER_CAPTAIN,
    CHARACTER_COUNT,
};