gText_Samuel_Welcome::
    .string "… … …\n"
    .string "… … …\l"
    .string "Open your mind, child…\p"
    .string "… … …\n"
    .string "… … …\l"
    .string "I said… open your mind!\n"
    .string "Let your thoughts be still.\p"
    .string "$"

gText_Samuel_Castform_Unused:: @@ See strings.c
	.string "And this is one of the friendly faces\n"
	.string "you'll see around town, Castform.{PAUSE 96}\p"

gText_Samuel_MainSpeech::
    .string "Can you feel it?\n"
    .string "That pulse between us…\l"
    .string "A thread pulled taut across time.\p"
    .string "I regret that we meet like this,\n"
    .string "only a whisper through the veil.\p"
    .string "But your heart… it is kind.\n"
    .string "It glows through the dark.\p"
    .string "Will you be my champion?\n"
    .string "One who acts with care and will?\p"
    .string "You need not answer now.\n"
    .string "But the moment will return…\l"
    .string "Just as all moments do.\p"
    .string "I wish to meet you face-to-face,\n"
    .string "beyond thought… beyond dreams.\p"
    .string "Keep calling out, keep reaching,\n"
	.string "as the veil thins between us.\n"
    .string "And I shall find you.\p"
    .string "$"

gText_Samuel_TellMeAboutYou::
	.string "Help me search for you…\n"
	.string "Tell me, child…$"

gText_Samuel_BoyOrGirl::
	.string "What do you look like?$"

gText_Samuel_ForgottenName::
	.string "And what should I call you?\n"
	.string "What is my potential champion's name?$"

gText_Samuel_SoYourePlayer::
	.string "{PLAYER}{KUN}?\n"
	.string "Your name is… {PLAYER}{KUN}?$"

gText_Samuel_JobIsYours::
    .string "Then I name you, {PLAYER}:\n"
    .string "Bearer of Care, and Guardian of Heart.\p"
    .string "Regressiion resistance walks within you.\p"
    .string "$"

gText_Samuel_TravelSafely::
	.string "Brace yourself, child.\n"
    .string "I have found a thread.\l"
    .string "It is time for us to meet.\p"
    .string "$"

gText_Samuel_ChooseTones::
	.string "Okay… Yes…\n"
	.string "Tell me more…$"
