gText_Samuel_Welcome::
    .string "… … …\n"
    .string "… … …\l"
    .string "Open your mind, child…\p"
    .string "… … …\n"
    .string "… … …\l"
    .string "I said… open your mind!\n"
    .string "Let your thoughts be still.\p"
    .string "$"

gText_Samuel_Castform_Unused:: @@ See strings.c
	.string "And this is one of the friendly faces\n"
	.string "you'll see around town, Castform.{PAUSE 96}\p"

gText_Samuel_MainSpeech::
    .string "Can you feel it?\n"
    .string "The thread that tugs at the edges?\p"
    .string "Faint, but real.\n"
    .string "I've been following it…\l"
    .string "I've been following you.\p"
    .string "This isn't how I hoped to reach you…\n"
    .string "In only a flicker. A whisper.\p"
    .string "So I need to know more…\n"
    .string "Enough to bring you fully through.\p"
    .string "This isn't the place for discussion.\n"
    .string "We must meet properly.\p"
    .string "Help me understand who you are.\n"
    .string "So I can find you… clearly.\p"
    .string "$"

gText_Samuel_TellMeAboutYou::
    .string "Tell me… what should I know?$"

gText_Samuel_BoyOrGirl::
	.string "What do you look like?$"

gText_Samuel_ForgottenName::
	.string "And what should I call you?$"

gText_Samuel_SoYourePlayer::
	.string "{PLAYER}{KUN}?\n"
	.string "Your name is… {PLAYER}{KUN}?$"

gText_Samuel_JobIsYours::
    .string "That’s enough, thank you.\n"
    .string "The shape of you has begun to form.\p"
    .string "You’ve carried more than most remember.\n"
    .string "It echoes in you still.\p"
    .string "$"

gText_Samuel_TravelSafely::
    .string "Hold still.\n"
    .string "The thread is steady now.\l"
    .string "I can pull you through.\p"
    .string "We will speak, in the quiet\n"
	.string "between moments…\p"
    .string "$"

gText_Samuel_ChooseTones::
	.string "Okay… Yes…\n"
	.string "Tell me more…$"
