gText_Samuel_Welcome::
	.string "… … …\n"
	.string "… … … Awake now, child.\l"
	.string "… … …\p"
	.string "I SAID AWAKE NOW!\p"
	.string "$"

gText_Samuel_Castform_Unused:: @@ See strings.c
	.string "And this is one of the friendly faces\n"
	.string "you'll see around town, Castform.{PAUSE 96}\p"

gText_Samuel_MainSpeech::
	.string "I have chosen you to be my champion.\n"
	.string "Some more flavour text.\l"
	.string "We need to hurry.\p"
	.string "I fear I won't recognise you\n"
	.string "when we eventually meet.\p"
	.string "$"

gText_Samuel_TellMeAboutYou::
	.string "Tell me, child…$"

gText_Samuel_BoyOrGirl::
	.string "Firstly, what do you look like?$"

gText_Samuel_ForgottenName::
	.string "And what should I call you?\n"
	.string "What is my new champion's name?$"

gText_Samuel_SoYourePlayer::
	.string "{PLAYER}{KUN}?\n"
	.string "Your name is… {PLAYER}{KUN}?$"

gText_Samuel_JobIsYours::
	.string "More flavour text.\p"
	.string "$"

gText_Samuel_TravelSafely::
	.string "Some exposition.\p"
	.string "$"

gText_Samuel_ChooseTones::
	.string "Okay… Please…\n"
	.string "Tell me more…$"
