VyratonIndoors_MayorsOffice_Text_ShouldReturn::
# 1 "data//maps/VyratonIndoors_MayorsOffice/text.pory"
	.string "I should probably stay a little bit\n"
	.string "longer, there's more to finish up…$"

VyratonIndoors_MayorsOffice_Text_KickStart::
# 8 "data//maps/VyratonIndoors_MayorsOffice/text.pory"
	.string "Well {PLAYER}, we should kick start\n"
	.string "business before it gets too late.\p"
	.string "I know you were unsure when I asked,\n"
	.string "so I brought some options for you.\p"
	.string "{PLAYER}… {PAUSE 40}It's time to claim a type\n"
	.string "for the Vyraton Town Pokémon Gym!\p"
	.string "I have for you, in my briefcase, a\n"
	.string "whopping eighteen different choices.\l"
	.string "Decide how to mold your gym's future!$"

VyratonIndoors_MayorsOffice_Text_CrackOpen::
# 22 "data//maps/VyratonIndoors_MayorsOffice/text.pory"
	.string "Now {PLAYER}, don't get shy on me!\n"
	.string "You have eighteen different choices…\p"
	.string "Crack open the briefcase, it's time\n"
	.string "for you to mold your gym's future!$"
