EventScript_ToggleableTransport_Indicators_AutoRunSet::
    callnative CreateToggleableTransportIcon_AutoRunSet
    playse SE_PIN
    delay 20
    callnative RemoveToggleableTransportIcon
    end

EventScript_ToggleableTransport_Indicators_AutoRunUnset::
    callnative CreateToggleableTransportIcon_AutoRunUnset
    playse SE_BOO
    delay 20
    callnative RemoveToggleableTransportIcon
    end

EventScript_ToggleableTransport_Indicators_FastSurfSet::
    callnative CreateToggleableTransportIcon_FastSurfSet
    playse SE_PIN
    delay 20
    callnative RemoveToggleableTransportIcon
    end

EventScript_ToggleableTransport_Indicators_FastSurfUnset::
    callnative CreateToggleableTransportIcon_FastSurfUnset
    playse SE_BOO
    delay 20
    callnative RemoveToggleableTransportIcon
    end

EventScript_ToggleableTransport_Indicators_FastBikeSet::
    callnative CreateToggleableTransportIcon_FastBikeSet
    playse SE_BIKE_BELL
    delay 20
    callnative RemoveToggleableTransportIcon
    end

EventScript_ToggleableTransport_Indicators_FastBikeUnset::
    callnative CreateToggleableTransportIcon_FastBikeUnset
    playse SE_BIKE_HOP
    delay 20
    callnative RemoveToggleableTransportIcon
    end

EventScript_ToggleableTransport_Indicators_AutoBikeSet::
    callnative CreateToggleableTransportIcon_AutoBikeSet
    playse SE_PIN
    delay 20
    callnative RemoveToggleableTransportIcon
    end

EventScript_ToggleableTransport_Indicators_AutoBikeUnset::
    callnative CreateToggleableTransportIcon_AutoBikeUnset
    playse SE_BOO
    delay 20
    callnative RemoveToggleableTransportIcon
    end
