VyratonIndoors_SSPathfinder_Text_IntroduceCaptain::
# 1 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Where d'ye think yer goin'?\n"
	.string "{PAUSE 60}Hold oan, forgot did ye?\p"
	.string "Every soul aboard this vessel gets a\n"
	.string "wee visit from the captain, giving\l"
	.string "out some advice fer yer travels.\p"
	.string "C'mon, noo, we've got a little bit o'\n"
	.string "time before the S.S. Pathfinder docks.\l"
	.string "May I come in?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou::
# 14 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Titchy room this is, 'tis a fair\n"
	.string "slight smaller than mae own.\l"
	.string "Name's Skip by the wae.\p"
	.string "{SPEAKER_NAME NAME_AUTO}With a name like that, I figured that\n"
	.string "I mae as well take tae the high seas.\l"
	.string "Been doing it a long time noo…\p"
	.string "After Vyraton, a new captain of\n"
	.string "the S.S. Pathfinder will be named.\l"
	.string "Ah'll be movin' ashore maself.\p"
	.string "Time tae bide near ma granddaughters,\n"
	.string "they've been after me fer years.\p"
	.string "I see ye also have a ticket tae the\n"
	.string "tiny place there yerself.\l"
	.string "Whit's brought ye tae it?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_WhateverItMayBe::
# 34 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "No matter if ye want a fresh start, or\n"
	.string "ye looki' fer a new challenge tae face,\l"
	.string "I know ye'll find success.\p"
	.string "Some folks just say the weather…$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_FreshStart::
# 43 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Yer after a fresh start?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_NewChallenge::
# 49 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Ye looki' fer a new challenge?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_Business::
# 55 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Yer just gaun fer business?$"

VyratonIndoors_SSPathfinder_Text_GranddaughtersAdvice::
# 61 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "{STR_VAR_1}\n"
	.string "A grand reason tae enjoy Vyraton!\p"
	.string "Let me give ye some advice that in\n"
	.string "fact came from ma girls o'er there.\l"
	.string "They telt me “Words are powerful”.\p"
	.string "Think oan that, the words ye say,\n"
	.string "the words ye hear and believe.\p"
	.string "They'll shape the wae the world see\n"
	.string "ye, and the wae ye see it.\l"
	.string "Carry that forward with ye.\p"
	.string "Ye'll have many an opportunity tae\n"
	.string "choose yer words wisely, ye know.\p"
	.string "Will ye be {COLOR BLUE}inspiring{COLOR DARK_GRAY}, {COLOR GREEN}humble{COLOR DARK_GRAY},\n"
	.string "{COLOR RED}dominant{COLOR DARK_GRAY} or maybe even {COLOR LIGHT_BLUE}cynical{COLOR DARK_GRAY}?$"

VyratonIndoors_SSPathfinder_Text_GranddaughtersAdvice_Inspired::
# 83 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Spoken like a true sailor! I'm sure\n"
	.string "the winds'll guide ye well and true.$"

VyratonIndoors_SSPathfinder_Text_GranddaughtersAdvice_Humble::
# 90 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Aye, a mark o' wisdom that, tae heed\n"
	.string "what's offered and learn as ye go.\l"
	.string "Dinnae worry, ye'll be grand.$"

VyratonIndoors_SSPathfinder_Text_GranddaughtersAdvice_Dominant::
# 98 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Ye got spirit, let's hope it's strong\n"
	.string "'nuff tae weather the storm ye make.\l"
	.string "{COLOR LIGHT_GRAY}{SHADOW WHITE}{FONT_SMALL}Even if ye come across a wee crass.{RESET_FONT}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}$"

VyratonIndoors_SSPathfinder_Text_GranddaughtersAdvice_Cynical::
# 106 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Ach! Ye'll ne'er steer true if ye're\n"
	.string "already sinkin' in yer mind.$"

VyratonIndoors_SSPathfinder_Text_SocialMedia::
# 113 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "{STR_VAR_1}\p"
	.string "An' that brings me tae this fancy-like\n"
	.string "thing, the kids call it PokéSphere.\l"
	.string "I reckon it's a sort of social caper.\p"
	.string "No for me, mind ye, but it's what ma\n"
	.string "granddaughters used tae pester me.\l"
	.string "It's oan the PokéNav ye see.\p"
	.string "Aye, a word can flee faster than\n"
	.string "a gale at sea, blisterin' oan by.\p"
	.string "A tale can shape how folk see ye,\n"
	.string "letting them in before ye've even\l"
	.string "the chance tae shake their hand.\p"
	.string "If ye wonderin' what the folk think,\n"
	.string "just have a gander at PokéSphere.\l"
	.string "It'll all be up tae ye, ma friend.\n"
	.string "Be mindful of that, eh?$"

VyratonIndoors_SSPathfinder_Text_SoundOfDocking::
# 134 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "And there's the sound o' us dockin',\n"
	.string "seems yer journey's just startin'.\l"
	.string "Ah'll see ye in Vyraton, aye?\p"
	.string "If ye come across ma granddaughters,\n"
	.string "be sure ye treat them kindly, eh?\l"
	.string "They're the light o' ma life, they are.\p"
	.string "It's been a real pleasure meetin' ye,\n"
	.string "wishin' ye fair winds and fairer luck.$"
