VyratonIndoors_SSPathfinder_Text_IntroduceCaptain::
# 1 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Where d'ye think yer goin'?\n"
	.string "{PAUSE 60}Hold on, forgot did ye?\p"
	.string "Every soul aboard this vessel gets a\n"
	.string "wee visit from the captain, giving\l"
	.string "out some advice fer yer travels.\p"
	.string "C'mon, noo, we've got a little bit o'\n"
	.string "time before the S.S. Pathfinder docks.\l"
	.string "May I come in?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou::
# 14 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Titchy room this, a fair slight\n"
	.string "smaller than me own. Ma name's Skip.\p"
	.string "{SPEAKER_NAME NAME_AUTO}With a name like that, I figured that\n"
	.string "I mae as well take tae the high seas.\l"
	.string "Been doing it a long time noo…\p"
	.string "After Vyraton, a new captain of\n"
	.string "the S.S. Pathfinder will be named.\l"
	.string "I'll be movin' ashore maself.\p"
	.string "Time tae bide near ma granddaughters,\n"
	.string "they've been after me fer years.\p"
	.string "I see ye also have a ticket tae the\n"
	.string "tiny place there yerself.\l"
	.string "Whit's brought ye tae it?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_FreshStart::
# 33 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Ye after a fresh start?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_NewChallenge::
# 39 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Ye looki' fer a new challenge?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_Business::
# 45 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Yer just gaun fer business?$"

VyratonIndoors_SSPathfinder_Text_GranddaughtersAdvice::
# 51 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "{STR_VAR_1}\n"
	.string "A grand reason tae enjoy Vyraton!\p"
	.string "Let me give ye some advice that in\n"
	.string "fact came from ma girls o'er there.\l"
	.string "They telt me “Words are powerful”.\p"
	.string "Think on that, the words ye say,\n"
	.string "the words ye hear and believe.\p"
	.string "They shape the way the world see\n"
	.string "ye, and the way ye see it.\l"
	.string "Carry that forward with ye.\p"
	.string "Ye'll have many an opportunity tae\n"
	.string "choose yer words wisely, ye know.\p"
	.string "Will ye be {COLOR BLUE}inspiring{COLOR DARK_GRAY}, {COLOR GREEN}humble{COLOR DARK_GRAY},\n"
	.string "{COLOR RED}dominant{COLOR DARK_GRAY} or maybe even {COLOR LIGHT_BLUE}cynical{COLOR DARK_GRAY}?$"
