VyratonIndoors_SSPathfinder_Text_IntroduceCaptain::
# 1 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Where d'you think you're goin'?\n"
	.string "{PAUSE 60}Hold on, forgot did you?\p"
	.string "Everybody aboard this vessel gets a\n"
	.string "wee visit from the captain, giving\l"
	.string "out some advice for your travels.\p"
	.string "Come on, now, we've got a little bit of\n"
	.string "time before the S.S. Pathfinder docks.\l"
	.string "May I come in?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou::
# 14 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "Titchy room this, more than a slight\n"
	.string "smaller than my own. My name's Skip.\p"
	.string "{SPEAKER_NAME NAME_AUTO}With a name like that, I figured that\n"
	.string "I might as well take to the high seas.\l"
	.string "Been doing it a long time now…\p"
	.string "After Vyraton, a new camptain of\n"
	.string "the S.S. Pathfinder will be named.\l"
	.string "I'll be moving ashore myself.\p"
	.string "Time to live with my granddaughters,\n"
	.string "they've been after me for years.\p"
	.string "I see you also have a ticket to the\n"
	.string "tiny place there yourself.\l"
	.string "What brings you to it?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_FreshStart::
# 33 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "You want a fresh start?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_NewChallenge::
# 39 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "You want a new challenge?$"

VyratonIndoors_SSPathfinder_Text_WhatBringsYou_Business::
# 45 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "You're just going for business?$"

VyratonIndoors_SSPathfinder_Text_GranddaughtersAdvice::
# 51 "data//maps/VyratonIndoors_SSPathfinder/text.pory"
	.string "{STR_VAR_1}\n"
	.string "A fine reason to enjoy Vyraton!\p"
	.string "Let me give you some advice that in\n"
	.string "fact came from my girls over there.\l"
	.string "They told me “Words are powerful”.\p"
	.string "Think on that, the words you say,\n"
	.string "the words you hear and believe.\p"
	.string "They shape the way the world see\n"
	.string "you, and the way you see it.\l"
	.string "Carry that forward with you.\p"
	.string "You'll have many an opportunity to\n"
	.string "choose your words wisely, you know.\p"
	.string "Will you be {COLOR LIGHT_BLUE}inspiring{COLOR DARK_GRAY}, {COLOR LIGHT_GREEN}humble{COLOR DARK_GRAY},\n"
	.string "{COLOR LIGHT_RED}dominant{COLOR DARK_GRAY} or maybe even {COLOR LIGHT_GRAY}cynical{COLOR DARK_GRAY}?\l"
	.string "It's up to you, my friend.$"
