# 1 "data//scripts/ikigai_characters/n.pory"
IkigaiCharacter_Movement_N_Shrug::
# 3 "data//scripts/ikigai_characters/n.pory"
	n_shrug
	step_end

# 6 "data//scripts/ikigai_characters/n.pory"
IkigaiCharacter_Movement_N_Headshake::
# 8 "data//scripts/ikigai_characters/n.pory"
	n_headshake
	step_end

# 11 "data//scripts/ikigai_characters/n.pory"
IkigaiCharacter_Movement_N_Pose::
# 13 "data//scripts/ikigai_characters/n.pory"
	n_pose
	step_end
