name: CI

on:
  push:
    branches:
      - dev-main
      - dev-upcoming
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3
        # build-essential and git are already installed

      - name: Poryscript Download
        uses: robinraju/release-downloader@v1
        with:
          repository: 'huderlem/poryscript'
          latest: true
          fileName: 'poryscript-linux.zip'
          extract: true
          out-file-path: 'tools'

      # - name: Print tools
      #   run: |
      #     echo "Contents:"
      #     ls
      #     echo ""
      #     echo "----------------------------------------"
      #     echo "Contents of tools:"
      #     ls tools
      #     echo ""
      #     echo "----------------------------------------"
      #     echo "Contents of tools/poryscript-linux.zip:"
      #     ls tools/poryscript-linux.zip
      #     echo ""
      #     echo "----------------------------------------"
      #     echo "Contents of tools/poryscript-linux:"
      #     ls tools/poryscript-linux
      #     echo ""
      #     echo "----------------------------------------"
      #     echo "Contents of poryscript:"
      #     ls tools/poryscript

      - name: Poryscript Install
        run: |
          sudo rm -rf tools/poryscript
          sudo mv tools/poryscript-linux tools/poryscript
          sudo chmod +x tools/poryscript/poryscript

      - name: ROM
        env:
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Test
        env:
          TEST: 1
        run: |
          make -j${nproc} check
